// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Elm")>]
[<assembly: AssemblyDescriptionAttribute("Helpers to write WPF application using Unidirectional flow (like Elm)")>]
[<assembly: GuidAttribute("052ff1a5-ec46-40bd-9be8-b77dd0b5ec76")>]
[<assembly: AssemblyProductAttribute("Elm")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Elm"
    let [<Literal>] AssemblyDescription = "Helpers to write WPF application using Unidirectional flow (like Elm)"
    let [<Literal>] Guid = "052ff1a5-ec46-40bd-9be8-b77dd0b5ec76"
    let [<Literal>] AssemblyProduct = "Elm"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
